title: John Kaeser
email: jakaeser44@gmail.com
description:
url: "http://jkaeser.github.io"
twitter_username:
github_username: jkaeser

markdown: kramdown

exclude:
  - 'package.json'
  - 'node_modules'
  - 'Gruntfile.js'
  - 'javascripts/src'
